### PR TITLE
Create network folders for branch removal

### PR DESCRIPTION
**Pull request by ross-spencer**
We can manage this repo more effectively without using multiple branches. We use folders to delineate network instead. Mainnet and preview are the only ones used as preprod isn't being used in Orcfax deployments right now.

@george-orcfax @gchartier <-- preparing to make this change this week if possible. Let me know if you have any preferred ways for me to coordinate this.

Connected to: https://github.com/orcfax/issues/issues/197

### CODE REVIEW

**Review by george-orcfax — APPROVED** [review]
Just let me know when you merge it, so that I can change immediately the URL in the monitoring.

**Comment by ross-spencer** [comment]
Thanks George.

@gchartier anything can be impacted your end?

**Comment by gchartier** [comment]
Looks great, just need to know when you plan to merge so I can push my code update to the index. 👌

**Comment by gchartier** [comment]
Actually, I just thought of something. If we plan to continue using this same repo moving forward and for different feed types in addition to `CER` feeds, then I think the name of the repo should probably not be `cer-feeds`.

Perhaps `feeds`, `active-feeds`, or `orcfax-feeds` would be a better name?

If we change the name then that makes the `feeds` folder in the repo redundant and can just have folders for each network at the top-level instead.

**Pull request merged**
